const ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    DELIVERY_NOT_FOUND: 'DELIVERY_NOT_FOUND',
    DRIVERS_NOT_FOUND: 'DRIVERS_NOT_FOUND',
    INVALID_ORDER_STATUS: 'INVALID_ORDER_STATUS',
    INVALID_DELIVERY_STATUS: 'INVALID_DELIVERY_STATUS',
    DRIVERS_NOT_AVAILABLE: 'DRIVERS_NOT_AVAILABLE',
    INVALID_MOCK_AMOUNT: 'INVALID_MOCK_AMOUNT',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    STORE_NOT_FOUND: 'STORE_NOT_FOUND',
    PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
    PRODUCT_NOT_AVAILABLE: 'PRODUCT_NOT_AVAILABLE',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    DUPLICATE_EMAIL_ADDRESS: 'DUPLICATE_EMAIL_ADDRESS',
    REQUIRED_FIELDS: 'REQUIRED_FIELDS',
    INVALID_DATA: 'INVALID_DATA',
    NO_SAVED_PRODUCTS: 'NO_SAVED_PRODUCTS',
    TYPE_NOT_FOUND: 'TYPE_NOT_FOUND'
};

export default ERROR_CODES;

/*Usuarios

USER_NOT_FOUND
USER_ALREADY_EXISTS
INVALID_USER_ROLE
INVALID_CREDENTIALS*/

/*Pedidos

ORDER_NOT_FOUND
ORDER_ITEMS_REQUIRED
INVALID_ORDER_STATUS
ORDER_ALREADY_DELIVERED*/

/*Entregas

DELIVERY_NOT_FOUND
DRIVER_NOT_AVAILABLE
DELIVERY_ALREADY_ASSIGNED
INVALID_DELIVERY_STATUS*/

/*Mocks

INVALID_MOCK_AMOUNT
MOCK_GENERATION_ERROR*/

/*Sistema

DATABASE_ERROR
INTERNAL_SERVER_ERROR
CONFIG_ERROR*/