const ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    DELIVERY_NOT_FOUND: 'DELIVERY_NOT_FOUND',
    DRIVERS_NOT_FOUND: 'DRIVERS_NOT_FOUND',
    INVALID_ORDER_STATUS: 'INVALID_ORDER_STATUS',
    INVALID_DELIVERY_STATUS: 'INVALID_DELIVERY_STATUS',
    DRIVERS_NOT_AVAILABLE: 'DRIVERS_NOT_AVAILABLE',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    STORE_NOT_FOUND: 'STORE_NOT_FOUND',
    PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
    PRODUCT_NOT_AVAILABLE: 'PRODUCT_NOT_AVAILABLE',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    DUPLICATE_EMAIL_ADDRESS: 'DUPLICATE_EMAIL_ADDRESS',
    REQUIRED_FIELDS: 'REQUIRED_FIELDS',
    INVALID_DATA: 'INVALID_DATA',
    INVALID_QUANTITY: 'INVALID_QUANTITY',
    NO_SAVED_PRODUCTS: 'NO_SAVED_PRODUCTS',
    TYPE_NOT_FOUND: 'TYPE_NOT_FOUND',
    SAVE_MOCKS_FAILED: 'SAVE_MOCKS_FAILED'
};

export default ERROR_CODES;

